# Use a imagem oficial do Node.js como base
FROM node:18

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app/frontend

# Copie os arquivos package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código-fonte para o contêiner
COPY . .

# Exponha a porta que o aplicativo usa (geralmente 3000 para Next.js)
EXPOSE 3000

# Comando para iniciar o aplicativo
CMD ["npm", "run", "dev"]