version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=rani
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=seu_usuario_real
      - POSTGRES_PASSWORD=sua_senha_real
      - POSTGRES_DB=nome_do_seu_banco_de_dados_real
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: